# Generated by Django 3.1.7 on 2021-03-20 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellbeingPollAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WellbeingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('weight', models.FloatField()),
                ('weight_reversed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WellbeingQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_score', models.FloatField()),
                ('wellbeing_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellbeing.wellbeingpollanswer')),
                ('wellbeing_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellbeing.wellbeingquestion')),
            ],
        ),
    ]
